#!/usr/bin/env python3
"""Regenerate the derived files from the posts in blog/.

Everything here is DERIVED. The posts are the only source of truth:
  date    <- filename prefix (YYYY-MM-DD-slug.html)
  title   <- the post's <h1>
  summary <- the post's <meta name="description">

Rewrites, in full, every time:
  feed.xml          Atom feed
  sitemap.xml       search-engine sitemap
  blog/index.html   only the region between the POSTS markers

Idempotent: running it twice in a row changes nothing. It never appends,
it replaces. Safe to run whenever, safe to run in CI.

  python3 build.py           regenerate
  python3 build.py --check   exit 1 if anything is stale (no writes)
"""
from __future__ import annotations

import glob
import html
import os
import re
import subprocess
import sys
from datetime import date

SITE = "https://adityac4.github.io"
AUTHOR = "Aditya Prashant Chaudhari"
FEED_TITLE = "Aditya Chaudhari — Posts"
FEED_SUBTITLE = "Technical writeups by Aditya Chaudhari."

BEGIN = "<!-- POSTS:BEGIN (generated by build.py — do not edit by hand) -->"
END = "<!-- POSTS:END -->"

MONTHS = ("January February March April May June July August September "
          "October November December").split()


def x(s: str) -> str:
    """Escape for XML/HTML text content."""
    return html.escape(s, quote=False)


def plain(fragment: str) -> str:
    """HTML fragment -> plain text. Headings carry markup (<code>, <em>);
    feed titles and link text must not."""
    txt = re.sub(r"<[^>]+>", "", fragment)
    return re.sub(r"\s+", " ", html.unescape(txt)).strip()


def read_posts() -> list[dict]:
    posts = []
    for path in glob.glob("blog/2*.html"):
        name = os.path.basename(path)
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})-", name)
        if not m:
            print(f"  skip (no date prefix): {name}", file=sys.stderr)
            continue
        src = open(path, encoding="utf-8").read()
        h1 = re.search(r"<h1[^>]*>(.*?)</h1>", src, re.S)
        desc = re.search(r'<meta name="description" content="(.*?)"', src, re.S)
        if not h1:
            sys.exit(f"error: {name} has no <h1> — cannot derive its title")
        if not desc:
            sys.exit(f"error: {name} has no meta description — cannot derive its summary")
        y, mo, d = (int(g) for g in m.groups())
        posts.append({
            "file": name,
            "iso": f"{y:04d}-{mo:02d}-{d:02d}",
            "human": f"{MONTHS[mo - 1]} {d}, {y}",
            "title": plain(h1.group(1)),
            "summary": plain(desc.group(1)),
        })
    # newest first; filename breaks ties so ordering is always deterministic
    return sorted(posts, key=lambda p: (p["iso"], p["file"]), reverse=True)


def home_lastmod() -> str:
    """Last commit date of index.html — or today, if it has uncommitted edits
    (those are about to ship) or git can't answer."""
    try:
        dirty = subprocess.run(["git", "status", "--porcelain", "--", "index.html"],
                               capture_output=True, text=True, timeout=10)
        if dirty.stdout.strip():
            return date.today().isoformat()
        out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", "index.html"],
                             capture_output=True, text=True, timeout=10)
        stamp = out.stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", stamp):
            return stamp
    except (OSError, subprocess.SubprocessError):
        pass
    return date.today().isoformat()


def build_feed(posts: list[dict]) -> str:
    updated = f"{posts[0]['iso']}T00:00:00Z" if posts else f"{date.today().isoformat()}T00:00:00Z"
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<feed xmlns="http://www.w3.org/2005/Atom">',
           f"  <title>{x(FEED_TITLE)}</title>",
           f"  <subtitle>{x(FEED_SUBTITLE)}</subtitle>",
           f'  <link href="{SITE}/feed.xml" rel="self" />',
           f'  <link href="{SITE}/blog/" />',
           f"  <id>{SITE}/</id>",
           f"  <updated>{updated}</updated>",
           "  <author>",
           f"    <name>{x(AUTHOR)}</name>",
           f"    <uri>{SITE}</uri>",
           "  </author>"]
    for p in posts:
        url = f"{SITE}/blog/{p['file']}"
        out += ["",
                "  <entry>",
                f"    <title>{x(p['title'])}</title>",
                f'    <link href="{url}" />',
                f"    <id>{url}</id>",
                f"    <published>{p['iso']}T00:00:00Z</published>",
                f"    <updated>{p['iso']}T00:00:00Z</updated>",
                f"    <summary>{x(p['summary'])}</summary>",
                "  </entry>"]
    out += ["</feed>", ""]
    return "\n".join(out)


def build_sitemap(posts: list[dict]) -> str:
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
           "  <url>", f"    <loc>{SITE}/</loc>",
           f"    <lastmod>{home_lastmod()}</lastmod>", "  </url>"]
    if posts:
        out += ["  <url>", f"    <loc>{SITE}/blog/</loc>",
                f"    <lastmod>{posts[0]['iso']}</lastmod>", "  </url>"]
    for p in posts:
        out += ["  <url>", f"    <loc>{SITE}/blog/{p['file']}</loc>",
                f"    <lastmod>{p['iso']}</lastmod>", "  </url>"]
    out += ["</urlset>", ""]
    return "\n".join(out)


def build_index(posts: list[dict], current: str) -> str:
    items = []
    for p in posts:
        items += ['          <li>',
                  f'            <span class="post-date">{x(p["human"])}</span> &mdash;',
                  f'            <a href="{x(p["file"])}">{x(p["title"])}</a>',
                  '          </li>']
    block = (f'        {BEGIN}\n        <ul class="post-list">\n'
             + "\n".join(items) + f'\n        </ul>\n        {END}')

    marked = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if marked.search(current):
        return marked.sub(lambda _: block.strip(), current, count=1)
    # first run: adopt the existing hand-written list and wrap it in markers
    plain = re.compile(r'[ \t]*<ul class="post-list">.*?</ul>', re.S)
    if not plain.search(current):
        sys.exit("error: blog/index.html has no <ul class=\"post-list\"> to replace")
    return plain.sub(lambda _: block, current, count=1)


def main() -> int:
    check = "--check" in sys.argv
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    posts = read_posts()
    if not posts:
        print("warning: no posts found under blog/", file=sys.stderr)

    index_path = "blog/index.html"
    targets = {
        "feed.xml": build_feed(posts),
        "sitemap.xml": build_sitemap(posts),
        index_path: build_index(posts, open(index_path, encoding="utf-8").read()),
    }

    stale = []
    for path, new in targets.items():
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == new:
            continue
        stale.append(path)
        if not check:
            open(path, "w", encoding="utf-8").write(new)

    noun = "post" if len(posts) == 1 else "posts"
    if check:
        if stale:
            print(f"stale: {', '.join(stale)}  (run: python3 build.py)")
            return 1
        print(f"up to date ({len(posts)} {noun})")
        return 0
    print(f"{len(posts)} {noun} -> " + (f"rewrote {', '.join(stale)}" if stale
                                        else "no changes (already up to date)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
